import type React from 'react';
import {
  Users,
  Palmtree,
  DollarSign,
  FileText,
  Scale,
  Stamp,
  Target,
  Megaphone,
  CalendarDays,
  Cake,
  FolderArchive,
  Calculator,
  Fingerprint,
  MapPin,
  Bell,
  MessageCircle,
  Package,
  ScrollText,
} from 'lucide-react';

/** Ícones partilhados entre menu horizontal e drawer mobile (evita duplicar JSX). */
export function intranetNavIconForPath(path: string): React.ReactNode {
  const map: Record<string, React.ReactNode> = {
    '/dashboard': <span className="text-[11px] font-bold">D</span>,
    '/notificacoes': <Bell className="h-4 w-4 shrink-0" />,
    '/portal/ferias': <Palmtree className="h-4 w-4 shrink-0" />,
    '/portal/faltas': <Target className="h-4 w-4 shrink-0" />,
    '/portal/recibos': <FileText className="h-4 w-4 shrink-0" />,
    '/portal/declaracoes': <FileText className="h-4 w-4 shrink-0" />,
    '/portal/requisicoes': <DollarSign className="h-4 w-4 shrink-0" />,
    '/capital-humano/colaboradores': <Users className="h-4 w-4 shrink-0" />,
    '/capital-humano/ferias': <Palmtree className="h-4 w-4 shrink-0" />,
    '/capital-humano/faltas': <Target className="h-4 w-4 shrink-0" />,
    '/capital-humano/recibos': <FileText className="h-4 w-4 shrink-0" />,
    '/capital-humano/processamento-salarial': <Calculator className="h-4 w-4 shrink-0" />,
    '/capital-humano/declaracoes': <FileText className="h-4 w-4 shrink-0" />,
    '/capital-humano/marcacoes-ponto': <Fingerprint className="h-4 w-4 shrink-0" />,
    '/capital-humano/zonas-trabalho': <MapPin className="h-4 w-4 shrink-0" />,
    '/financas/requisicoes': <DollarSign className="h-4 w-4 shrink-0" />,
    '/financas/bancos': <DollarSign className="h-4 w-4 shrink-0" />,
    '/financas/contas-bancarias': <DollarSign className="h-4 w-4 shrink-0" />,
    '/financas/tesouraria': <DollarSign className="h-4 w-4 shrink-0" />,
    '/financas/centros-custo': <DollarSign className="h-4 w-4 shrink-0" />,
    '/financas/projectos': <DollarSign className="h-4 w-4 shrink-0" />,
    '/financas/relatorios': <FileText className="h-4 w-4 shrink-0" />,
    '/contabilidade/pagamentos': <FileText className="h-4 w-4 shrink-0" />,
    '/contabilidade/pendencias': <Stamp className="h-4 w-4 shrink-0" />,
    '/secretaria/reunioes': <Stamp className="h-4 w-4 shrink-0" />,
    '/secretaria/actas': <FileText className="h-4 w-4 shrink-0" />,
    '/secretaria/documentos': <FileText className="h-4 w-4 shrink-0" />,
    '/gestao-documentos': <FolderArchive className="h-4 w-4 shrink-0" />,
    '/patrimonio': <Package className="h-4 w-4 shrink-0" />,
    '/secretaria/correspondencias': <MessageCircle className="h-4 w-4 shrink-0" />,
    '/secretaria/arquivo': <Scale className="h-4 w-4 shrink-0" />,
    '/juridico/contratos': <Scale className="h-4 w-4 shrink-0" />,
    '/juridico/processos': <Scale className="h-4 w-4 shrink-0" />,
    '/juridico/processos-disciplinares': <Scale className="h-4 w-4 shrink-0" />,
    '/juridico/prazos': <Stamp className="h-4 w-4 shrink-0" />,
    '/juridico/riscos': <Target className="h-4 w-4 shrink-0" />,
    '/juridico/rescisoes': <Scale className="h-4 w-4 shrink-0" />,
    '/juridico/arquivo': <Scale className="h-4 w-4 shrink-0" />,
    '/planeamento/relatorios': <Target className="h-4 w-4 shrink-0" />,
    '/planeamento/consolidacao': <Target className="h-4 w-4 shrink-0" />,
    '/planeamento/dashboard': <Target className="h-4 w-4 shrink-0" />,
    '/comunicacao-interna/noticias': <Megaphone className="h-4 w-4 shrink-0" />,
    '/comunicacao-interna/eventos': <CalendarDays className="h-4 w-4 shrink-0" />,
    '/comunicacao-interna/comunicados': <ScrollText className="h-4 w-4 shrink-0" />,
    '/comunicacao-interna/aniversarios': <Cake className="h-4 w-4 shrink-0" />,
  };
  return map[path] ?? null;
}
