-- =============================================================================
-- Facturação: activar por empresa + zona de facturação + tabelas (factura, produto)
-- =============================================================================

-- 1) Campos na empresa
alter table public.empresas
  add column if not exists facturacao_activa boolean not null default false,
  add column if not exists zona_facturacao text null;

-- 2) Tabela de facturas (header)
create table if not exists public.factura (
  id bigint generated by default as identity not null,
  -- Empresa (código/índice vindo do ERP / Primavera)
  empresa_id smallint null,
  id_factura text null,
  num_factura smallint null,
  tipo text null,
  serie smallint null,
  cliente text null,
  nif text null,
  total_factura text null,
  total_iva text null,
  tota_merc text null,
  ultima_actualizacao text null,
  created_at timestamp with time zone not null default now(),
  constraint factura_pkey primary key (id)
);

create index if not exists idx_factura_empresa on public.factura (empresa_id);
create index if not exists idx_factura_id_factura on public.factura (id_factura);

-- 3) Tabela de produtos/linhas por factura
create table if not exists public.produto (
  id bigint generated by default as identity not null,
  id_factura text null,
  num_linha smallint null,
  cod_artigo text null,
  descricao text null,
  quantidade text null,
  preco text null,
  total_liquido text null,
  total_iva text null,
  taxa_iva text null,
  created_at timestamp with time zone not null default now(),
  constraint produto_pkey primary key (id)
);

create index if not exists idx_produto_id_factura on public.produto (id_factura);

